/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SudokuRouteImport } from './routes/sudoku'
import { Route as IndexRouteImport } from './routes/index'

const SudokuRoute = SudokuRouteImport.update({
  id: '/sudoku',
  path: '/sudoku',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sudoku': typeof SudokuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sudoku': typeof SudokuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sudoku': typeof SudokuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sudoku'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sudoku'
  id: '__root__' | '/' | '/sudoku'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SudokuRoute: typeof SudokuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sudoku': {
      id: '/sudoku'
      path: '/sudoku'
      fullPath: '/sudoku'
      preLoaderRoute: typeof SudokuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SudokuRoute: SudokuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
